name: Simple GitHub Action

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    download_qqwry_dat:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Download qqwry.dat
              run: |
                  wget -O qqwry.dat https://raw.githubusercontent.com/FW27623/qqwry/main/qqwry.dat

            - name: Set workspace directory
              run: |
                  mkdir my_folder
                  mv * test  
                  cd test
            - name: Copy qqwry.dat to repository
              env:
                  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
                  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
              run: |
                  git remote -v
                  git add qqwry.dat
                  git commit -m "update qqwry.dat"
                  git push
                  
