name: Simple GitHub Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download_qqwry_dat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download new qqwry.dat
        run: |
          wget -O qqwry.dat https://raw.githubusercontent.com/FW27623/qqwry/main/qqwry.dat
          
      - name: Copy qqwry.dat to repository
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: |
          mkdir -p data
          rm data/qqwry.dat
          mv qqwry.dat data/qqwry.dat
          stat data/qqwry.dat
          touch data/qqwry.dat 
          stat data/qqwry.dat
          
